import { interval, type TupleOf } from "../lib/util.js";

/** A fixed-length tuple with the given fill. */
export function fill<Dimension extends number, Fill>(
  dimension: Dimension,
  fill: Fill,
): TupleOf<Dimension, Fill> {
  return new Array(dimension).fill(fill) as TupleOf<Dimension, Fill>;
}

/** An (small) n-dimensional vector of numbers. */
export class Vector<Dimension extends number> {
  readonly dimension: Dimension;
  readonly value: TupleOf<Dimension, number>;

  constructor(value: TupleOf<Dimension, number>) {
    this.dimension = value.length as Dimension;
    this.value = value;
  }

  static from<const Dimension extends number>(
    _dimension: Dimension,
    value: TupleOf<Dimension, number>,
  ): Vector<Dimension> {
    return new Vector(value);
  }

  /** Parse a string, dumped from a vector, into a vector. */
  static parse<const Dimension extends number>(
    dimension: Dimension,
    serialized: string,
  ): Vector<Dimension> {
    const value = serialized.split(",").map((x) => Number(x));
    if (value.length !== dimension) {
      throw new Error(
        `Invalid vector length: ${value.join(", ")} must have length ${dimension.toString()}`,
      );
    }
    return new Vector(value as TupleOf<Dimension, number>);
  }

  /** Convert the vector to a string, which can be parsed back. */
  toString(): string {
    return this.value.join(",");
  }

  /** Get the value at the given dimension. */
  get(dimension: number): number {
    if (dimension < 0 || dimension >= this.dimension) {
      throw new Error(
        `Out of bounds: [${this.toString()}][${dimension.toString()}]`,
      );
    }
    return this.value[dimension]!;
  }

  /** Does this vector equal the given one? */
  equals(other: Vector<Dimension>): boolean {
    return this.value.every((v, d) => v === other.value[d]);
  }
}

/**
 * A convex cone with a given vertex, generated by the unit vectors along the
 * non-strict dimensions.
 */
export class Cone<Dimension extends number> {
  readonly vertex: Vector<Dimension>;
  readonly strict: TupleOf<Dimension, boolean>;

  constructor(vertex: Vector<Dimension>, strict: TupleOf<Dimension, boolean>) {
    this.vertex = vertex;
    this.strict = strict;
  }

  static from<const Dimension extends number>(
    dimension: Dimension,
    vertex: Vector<Dimension> | TupleOf<Dimension, number>,
    strict: TupleOf<Dimension, boolean>,
  ) {
    return new Cone(
      vertex instanceof Vector ? vertex : Vector.from(dimension, vertex),
      strict,
    );
  }

  /** Does this cone equal the given one? */
  equals(other: Cone<Dimension>): boolean {
    return (
      this.vertex.equals(other.vertex) &&
      this.strict.every((strict, d) => strict === other.strict[d])
    );
  }

  /** Does this cone include the given vector? */
  includes(vector: Vector<Dimension>): boolean {
    return this.vertex.value.every((v, d) => {
      if (this.strict[d]) {
        return v === vector.value[d]!;
      } else {
        return v <= vector.value[d]!;
      }
    });
  }

  /** Does this cone contain the given cone? */
  contains(other: Cone<Dimension>): boolean {
    return (
      this.includes(other.vertex) &&
      this.strict.every((strict, d) => !strict || other.strict[d])
    );
  }

  /** Deduplicate a list of cones. */
  static dedupe<const Dimension extends number>(
    cones: Cone<Dimension>[],
  ): Cone<Dimension>[] {
    const deduped: Cone<Dimension>[] = [];
    for (const cone of cones) {
      if (!deduped.some((other) => other.equals(cone))) {
        deduped.push(cone);
      }
    }
    return deduped;
  }

  /**
   * Get the set of cones that aren't contained by any other cone. In other
   * words, these are the maximal elements in the subposet of cones under
   * containment.
   */
  static maxima<const Dimension extends number>(
    cones: Cone<Dimension>[],
  ): Cone<Dimension>[] {
    const deduped = Cone.dedupe(cones);
    return deduped.filter(
      (cone) =>
        !deduped.some((other) => cone !== other && other.contains(cone)),
    );
  }

  /**
   * Get the set of cones that either:
   * - aren't contained by any other cone, or
   * - don't contain any other cone.
   * In other words, these are the minimal and maximal elements in the subposet
   * of cones under containment.
   */
  static extrema<const Dimension extends number>(
    cones: Cone<Dimension>[],
  ): Cone<Dimension>[] {
    const deduped = Cone.dedupe(cones);
    const result: Cone<Dimension>[] = [];
    for (const cone of deduped) {
      if (
        !deduped.some((other) => cone !== other && other.contains(cone)) ||
        !deduped.some((other) => cone !== other && cone.contains(other))
      ) {
        result.push(cone);
      }
    }
    return result;
  }

  [Symbol.for("nodejs.util.inspect.custom")](): string {
    const result = [];
    for (const d of interval(0, this.vertex.dimension - 1)) {
      result.push(
        `${this.vertex.get(d).toString()}${this.strict[d] ? "=" : "+"}`,
      );
    }
    return `Cone(${result.join(", ")})`;
  }
}
